---
  - name: "install epel"
    become: yes
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=present
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    tags:
      - guacamole

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    tags:
      - guacamole

  - name: "install guacamole"
    become: yes
    yum: name="{{ item }}" state=present
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    with_items:
      - guacd
      - libguac-client-rdp
      - libguac-client-vnc
      - libguac-client-ssh
      - guacamole
    tags:
      - guacamole

  - name: "copy user-mappiing.xml"
    become: yes
    template: src=user-mapping.xml dest=/etc/guacamole/user-mapping.xml owner=root group=root mode=0755
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    tags:
      - guacamole

  - name: "Update the /etc/tomcat/tomcat.conf /dev/random to /dev/urandom"
    become: yes
    lineinfile:
      dest: /etc/tomcat/tomcat.conf
      regexp: "^JAVA_OPTS"
      line: 'JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom"'
      insertafter: EOF
      state: present
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    tags:
      - guacamole

  - name: "enable guacd"
    become: yes
    service: name={{ item }} enabled=yes state=restarted
    when: guac_pass is defined and guac_pass !="" and inventory_hostname == groups["nfs"][0]
    with_items:
      - guacd
      - tomcat
    tags:
      - guacamole
