---
  - name: "install epel"
    become: yes
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=present
    when: xrdpuser_pass is defined and xrdpuser_pass !=""
    tags:
      - guacamole

  - name: "install guacamole"
    become: yes
    yum: name="{{ item }}" state=present
    when: guac_pass is defined and guac_pass !=""
    with_items:
      - guacd
      - libguac-client-rdp
      - libguac-client-vnc
      - libguac-client-ssh
      - guacamole
    tags:
      - guacamole

  - name: "copy user-mappiing.xml"
    become: yes
    template: src=user-mapping.xml dest=/etc/guacamole/user-mapping.xml owner=root group=root mode=0755
    when: guac_pass is defined and guac_pass !=""
    tags:
      - guacamole

  - name: "enable xrdp"
    become: yes
    service: name={{ item }} enabled=yes state=started
    when: guac_pass is defined and guac_pass !=""
    with_items:
      - guacd
      - tomcat
    tags:
      - guacamole
