---
  - name: "check grid_install_media"
    become: yes
    shell: cat /media/grid/response/grid_install.rsp
    ignore_errors: true
    when: inventory_hostname == groups["dbserver"][0]
    register: gridmedia_rerult
    tags:
      - gridmedia
      - copymedia

  - name: "crete directory"
    become: yes
    file: path=/media/grid state=directory
    when: inventory_hostname == groups["dbserver"][0] and gridmedia_rerult.rc != 0
    tags:
      - gridmedia
      - copymedia


  - name: "copy gridmedia"
    become: yes
    unarchive: src="/media/{{ item }}" dest=/media/grid
    with_items:
      - "{{ GRID_MEDIA1 }}"
      - "{{ GRID_MEDIA2 }}"
    when: inventory_hostname == groups["dbserver"][0] and gridmedia_rerult.rc != 0
    tags:
      - gridmedia
      - copymedia


  - name: "check db_install_media"
    become: yes
    shell: cat /media/database/response/db_install.rsp
    ignore_errors: true
    when: inventory_hostname == groups["dbserver"][0]
    register: dbmedia_rerult
    tags:
      - dbmedia
      - copymedia


  - name: "crete directory"
    become: yes
    file: path=/media/database state=directory
    when: inventory_hostname == groups["dbserver"][0] and dbmedia_rerult.rc != 0
    tags:
      - dbmedia
      - copymedia

  - name: "copy dbmedia"
    become: yes
    unarchive: src="/media/{{ item }}" dest=/media/database
    with_items:
      - "{{ DB_MEDIA1 }}"
      - "{{ DB_MEDIA2 }}"
    when: inventory_hostname == groups["dbserver"][0] and dbmedia_rerult.rc != 0
    tags:
      - dbmedia
      - copymedia
