---
  - name: "check grid_install_media"
    become: yes
    shell: cat /media/grid/response/grid_install.rsp
    ignore_errors: true
    register: gridmedia_rerult
    tags:
      - gridmedia
      - copymedia

  - name: "copy gridmedia"
    become: yes
    copy: src="/media/{{ item }}" dest="/media/{{ item }}"
    with_items
      - {{ GRID_MEDIA1 }}
      - {{ GRID_MEDIA2 }}
    when: gridmedia_rerult.rc != 0
    tags:
      - gridmedia
      - copymedia


  - name: "check db_install_media"
    become: yes
    shell: cat /media/database/response/db_install.rsp
    ignore_errors: true
    register: dbmedia_rerult
    tags:
      - dbmedia
      - copymedia

  - name: "copy dbmedia"
    become: yes
    copy: src="/media/{{ item }}" dest="/media/{{ item }}"
    with_items
      - {{ DB_MEDIA1 }}
      - {{ DB_MEDIA2 }}
    when: dbmedia_rerult.rc != 0
    tags:
      - dbmedia
      - copymedia
