---
  - name: "create /etc/vxlan"
    become: yes
    file: path=/etc/vxlan state=directory owner=root group=root mode=0755
  - name: "create all.ip"
    become: yes
    template: src=all.ip.j2 dest=/etc/vxlan/all.ip owner=root group=root mode=0644
