---
  - name: "cvu"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/runcluvfy.sh stage -pre crsinst -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    register: cvu_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvucrsinst
      
  - debug: var=cvu_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvucrsinst

  - name: "cvu_ssa"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/runcluvfy.sh comp ssa -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %} -s {{ VOTE_DEV }}"
    register: cvussa_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvucrsinst
      
  - debug: var=cvussa_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvucrsinst

  - name: "cvudbinst"
    become: yes
    become_user: oracle
    shell: "{{ GRID_ORACLE_HOME }}/runcluvfy.sh stage -pre dbinst -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    register: cvudbinst_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvudbinst
      
  - debug: var=cvudbinst_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvudbinst

  - name: "cvudbca"
    become: yes
    become_user: oracle
    shell: "{{ GRID_ORACLE_HOME }}/runcluvfy.sh stage -pre dbcfg -n {% for host in groups['dbserver']  %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %} -d {{ ORA_ORACLE_HOME }}"
    register: cvudbca_result
    ignore_errors: True
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvudbca
      
  - debug: var=cvudbca_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - cvudbca
