---
  - name: "mgmtdb"
    become: yes
    become_user: grid
    shell: "export ORACLE_HOME={{ GRID_ORACLE_HOME }} && {{ GRID_ORACLE_HOME }}/gridSetup.sh -executeConfigTools -responseFile /home/grid/asm.rsp -silent"
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    register: asmca_result
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - mgmtdb
      - gridinstall
      - installdbca

  - debug: var=asmca_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - mgmtdb
      - gridinstall
      - installdbca

  - name: "crsctl"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/bin/crsctl status resource -t"
    register: crsctl_result
    tags:
      - mgmtdb
      - gridinstall
      - installdbca

  - debug: var=crsctl_result.stdout_lines
    tags:
      - mgmtdb
      - gridinstall
      - installdbca
