####################################################
guac_pass: Guac123!
vnc_pass: Vnc123!
####################################################
####################################################
#### docker user specific value  ###################
DOCKERSUBNET: "10.153.0.0/16"
BRNAME: "raconxx"
DOCKER_VOLUME_PATH: "/rac_on_docker"
####################################################
####common VIRT_TYPE specific value ################
DELETE_CMD_OPS: "-f"
DELETE_CMD: "docker rm {{ DELETE_CMD_OPS }}"
START_CMD: "docker start"
START_CMD_OPS: ""
STOP_CMD: "docker stop"
STOP_CMD_OPS: ""
INSTALL_OPS: "-ignoreSysprereqs -ignorePrereq"
DHCPCLIENT: ""
####################################################
####docker system  specific value ##################
IMAGE: "s4ragent/rac_on_xx:OEL7"
#CAP_OPS: "--cap-add=NET_ADMIN"
DOCKER_CAPS: "--privileged=true --security-opt seccomp=unconfined"
#DOCKER_CAPS: "--cap-add=ALL --security-opt=seccomp=unconfined"
DOCKER_START_OPS: "--restart=always"
TMPFS_OPS: "--shm-size=1200m"
####################################################
WindowManager: "xfce"
#####for NFS option values
##### device size = base_size + multi_size * node count
storage_type: "nfs"
ORA_DATA: /u01/oradata
VOTE_DEV: /u01/oradata/vote.img
VOTE_BASE_SIZE: 5120
VOTE_MULTI_SIZE: 1024
VOTE_DISKGROUP_NAME: VOTE
DATA_DEV: /u01/oradata/data.img
DATA_BASE_SIZE: 5120
DATA_MULTI_SIZE: 1024
DATA_DISKGROUP_NAME: DATA
FRA_DEV: /u01/oradata/fra.img
FRA_BASE_SIZE: 5120
FRA_MULTI_SIZE: 0
FRA_DISKGROUP_NAME: FRA
ASM_STRING: /u01/oradata/*
