---
  - name: "check oracle-release"
    become: yes
    shell: cat /etc/oracle-release
    ignore_errors: true
    register: centos2oel_rerult
    tags:
      - centos2oel

  - name: "centos2oel"
    become: yes
    shell: curl -O https://linux.oracle.com/switch/centos2ol.sh && sh centos2ol.sh
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel

  - name: reboot
    become: yes
    shell: sleep 2 && shutdown -r now
    when: centos2oel_rerult.rc != 0
    async: 1
    poll: 0
    ignore_errors: true
    tags:
      - centos2oel
 
  - name: wait for the server to go down (reboot)
    local_action: wait_for host= {{ ansible_host }} port=22 state=stopped
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel
      
  - name: wait for the server to come up
    local_action: wait_for host= {{ ansible_host }} port=22 delay=60  timeout=300
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel
