---
  - name: "disable fastestmirror"
    become: yes
    shell: sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf 
    ignore_errors: true
    tags:
      - centos2oel

  - name: "yum clean all"
    become: yes
    shell: yum -y clean all
    ignore_errors: true
    tags:
      - centos2oel

  - name: "check oracle-release"
    become: yes
    shell: cat /etc/oracle-release
    ignore_errors: true
    register: centos2oel_rerult
    tags:
      - centos2oel

  - name: "centos2oel"
    become: yes
    shell: curl -O https://linux.oracle.com/switch/centos2ol.sh && sh centos2ol.sh
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel

  - name: reboot
    become: yes
    shell: sleep 2 && shutdown -r now
    when: centos2oel_rerult.rc != 0
    async: 1
    poll: 0
    ignore_errors: true
    tags:
      - centos2oel

#  - name: wait for the server to come up
#    local_action: wait_for host= {{ hostvars[item]['ansible_ssh_host'] }} port=22 delay=120  timeout=300
#    with_items: "{{ play_hosts }}"
#    run_once: true
#    when: centos2oel_rerult.rc != 0
#    tags:
#      - centos2oel

  - name: "sleep 360s"
    local_action: shell sleep 360s
    run_once: true
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel

  - name: "centos2oel distro-sync"
    become: yes
    shell: yum -y distro-sync
    when: centos2oel_rerult.rc != 0
    tags:
      - centos2oel

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    tags:
      - centos2oel

