---
  - name: "centos2oel"
    become: yes
    shell: curl -O https://linux.oracle.com/switch/centos2ol.sh && sh centos2ol.sh
    ignore_errors: true
    register: centos2oel_rerult
    tags:
      - centos2oel
 
  - name: reboot
    shell: sleep 2s && /sbin/reboot
    when: centos2oel_rerult.rc == 0
    tags:
      - centos2oel

  - name: wait for the server to go down (reboot)
    local_action: wait_for host= {{ ansible_ssh_host }} port=22 state=stopped
    when: centos2oel_rerult.rc == 0
    tags:
      - centos2oel
      
  - name: wait for the server to come up
    local_action: wait_for host= {{ ansible_ssh_host }} port=22 delay=60
    when: centos2oel_rerult.rc == 0
    tags:
      - centos2oel
