---
  - name: "Partition additional disks"
    become: yes
    shell: |
      if
        [ -b {{ data_disk_dev }} ]
      then
        [ -b {{ data_disk_dev }}1 ] || parted --script "{{ data_disk_dev }}" mklabel gpt mkpart primary 1MiB 100%
      fi
    args:
      creates: '{{ data_disk_dev }}1'
      executable: '/bin/bash'
    when: data_disk_dev is defined and data_disk_dev !=""
    tags:
      - oraclehome

  - name: "fdisk data_disk_dev"
    become: yes
    filesystem: fstype=xfs dev={{ data_disk_dev }}1
    when: data_disk_dev is defined and data_disk_dev !=""
    tags:
      - oraclehome

  - name: "create data_disk mountpoint"
    become: yes
    file: path={{ data_disk_mountpoint }} state=directory owner=grid group=oinstall mode=0755
    when: data_disk_dev is defined and data_disk_dev !=""
    tags:
      - oraclehome

  - name: "mount data_disk_dev"
    become: yes
    mount: name={{ data_disk_mountpoint }} src={{ data_disk_dev }}1 fstype=xfs opts=defaults passno=0 dump=0 state=mounted
    when: data_disk_dev is defined and data_disk_dev !=""
    tags:
      - oraclehome