---
  - name: "install nfs packages"
    become: yes
    yum: name=nfs-utils state=present
    tags:
      - nfsclient

  - name: "mount oradata"
    become: yes
    mount: name={{ ORA_DATA }} src="{{ NFS_SERVER }}:/" fstype=nfs opts=rw,bg,hard,nointr,tcp,vers=4,timeo=600,actimeo=0 state=mounted
    tags:
      - nfsclient

  - name: "chown oradata"
    become: yes
    file: path={{ ORA_DATA }} state=directory owner=grid group=oinstall mode=0775
    tags:
      - nfsclient

  - name: "create asm device vote"
    shell: dd if=/dev/zero of={{ VOTE_DEV }} bs=1M count=$VOTE_DEV_SIZE
    args:
      creates: {{ VOTE_DEV }}
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - nfsclient
