---
  - name: "install nfs packages"
    become: yes
    yum: name=nfs-utils state=present
    tags:
      - nfsclient

  - name: "mount oradata"
    become: yes
    mount: name={{ ORA_DATA }} src="{{ NFS_SERVER }}:/" fstype=nfs opts=rw,bg,hard,nointr,tcp,vers=4,timeo=600,actimeo=0 state=mounted
    tags:
      - nfsclient

  - name: "chown oradata"
    become: yes
    file: path={{ ORA_DATA }} state=directory owner=grid group=oinstall mode=0775
    tags:
      - nfsclient

  - name: "create asm device vote"
    become: yes
    shell: dd if=/dev/zero of={{ item.name }} bs=1M count={{ item.size }}
    args:
      creates: "{{ item.name }}"
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - { name: "{{ VOTE_DEV }}", size: "{{ VOTE_MULTI_SIZE * groups['dbserver'] | length  }}" }
    tags:
      - nfsclient

  - name: "chown oradata"
    become: yes
    file: path={{ item.name }} state=present owner=grid group=oinstall mode=0660
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - { name: "{{ VOTE_DEV }}" }
    tags:
      - nfsclient

 
