---
  - name: "test"
    debug: msg={% for host in play_hosts %}{{ hostvars[host]['NODENAME'] }}{% if not loop.last %},{% endif %}{% endfor %}
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - dbca
