---
  - name: "create db.rsp"
    become: yes
    template: src=db.rsp.j2 dest=/home/oracle/db.rsp owner=oracle group=oinstall mode=0644
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - createdbrsp
      - dbinstall
      - installdbca

  - name: "runInstaller(db)"
    become: yes
    become_user: oracle
    shell: "{{ MEDIA_PATH }}/database/runInstaller -silent -responseFile /home/oracle/db.rsp -waitforcompletion {{ INSTALL_OPS }}"
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    when: inventory_hostname == groups["dbserver"][0]
    ignore_errors: True
    register: runinstallerdb_result
    tags:
      - runinstallerdb
      - dbinstall
      - installdbca

  - debug: var=runinstallerdb_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    failed_when: runinstallerdb_result.rc !=0 and runinstallergrid_result.rc != 250
    tags:
      - runinstallerdb
      - dbinstall
      - installdbca

  - name: "db root.sh"
    become: yes
    shell: "{{ ORA_ORACLE_HOME }}/root.sh -silent"
    register: dbrootsh_result
    tags:
      - dbrootsh
      - dbinstall
      - installdbca

  - debug: var=dbrootsh_result.stdout_lines
    tags:
      - dbrootsh
      - dbinstall
      - installdbca
