---
  - name: "create db.rsp"
    become: yes
    template: src=db.rsp.j2 dest=/home/oracle/db.rsp owner=oracle group=oinstall mode=0644
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - createdbrsp
      - dbinstall

  - name: "runInstaller(db)"
    become: yes
    become_user: oracle
    shell: /media/database/runInstaller -silent -responseFile /home/oracle/db.rsp -waitforcompletion {{ INSTALL_OPS }}
    when: inventory_hostname == groups["dbserver"][0]
    register: runinstallerdb_result
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    tags:
      - runinstallerdb
      - dbinstall

  - debug: var=runinstallerdb_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - runinstallerdb
      - dbinstall

  - name: "db root.sh"
    become: yes
    shell: "{{ ORA_ORACLE_HOME }}/root.sh -silent"
    register: dbrootsh_result
    tags:
      - dbrootsh
      - dbinstall

  - debug: var=dbrootsh_result.stdout_lines
    tags:
      - dbrootsh
      - dbinstall