---
  - name: "install epel"
    become: yes
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=present
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc
      
#environment groups must "@^"
#packages group must"@"
  - name: "install vnc,Xfce,firefox"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
#      - "@^graphical-server-environment"
      - "@xfce-desktop"
      - tigervnc-server
      - firefox
      - unzip
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: Copy vnc service file
    become: yes
    shell: "cp /usr/lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:{{item.0 + 1}}.service"
    with_indexed_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: edit vnc service file
    become: yes
    shell: "sed -i -e 's/<USER>/{{ item.1 }}/g' /etc/systemd/system/vncserver@:{{item.0 + 1}}.service"
    with_indexed_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: "crete directory"
    become: yes
    file: path="/home/{{ item }}/.vnc" state=directory mode=0755 group=oinstall owner={{ item }}
    with_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc
      
  - name: "crete vncpasswd"
    become: yes
    shell: "echo {{ vnc_pass }} | vncpasswd -f > /home/{{ item }}/.vnc/passwd"
    with_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc
      
  - name: "chown directory"
    become: yes
    file: path="/home/{{ item }}/.vnc/password" mode=0600 group=oinstall owner={{ item }}
    with_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: "crete vncpasswd"
    become: yes
    shell: systemctl daemon-reload
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: start vnc service
    become: yes
    service: name="vncserver@:{{item.0 + 1}}.service" state=restarted enabled=yes
    with_indexed_items:
      - oracle
      - grid
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc

  - name: "crete directory"
    become: yes
    file: path={{ MEDIA_PATH }} state=directory mode=0777 group=oinstall owner=oracle
    when: vnc_pass is defined and vnc_pass !=""
    tags:
      - vnc
