---
  - name: "create addn-hosts"
    become: yes
    template: src=addn-hosts.j2 dest=/etc/addn-hosts owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy dns.conf"
    become: yes
    copy: src=dns.conf dest=/etc/NetworkManager/conf.d/dns.conf owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy hosts"
    become: yes
    copy: src=hosts dest=/etc/NetworkManager/dnsmasq.d/hosts owner=root group=root mode=0644
    tags:
      - dnsmasq
      
  - name: "restart networkManager"
    become: yes
    service: name=NetworkManager.service state=restarted
    tags:
      - dnsmasq

  - name: "create sethosts"
    become: yes
    template: src=30_hostname.j2 dest=/etc/NetworkManager/dispatcher.d/30_hostname owner=root group=root mode=0700
    tags:
      - hostname

  - name: "change hostname"
    become: yes
    shell: bash /etc/NetworkManager/dispatcher.d/30_hostname vxlan0 up
    tags:
      - hostname

  - name: "create setresolvconf"
    become: yes
    template: src=31_resolvconf.j2 dest=/etc/NetworkManager/dispatcher.d/31_resolvconf owner=root group=root mode=0700
    tags:
      - resolvconf

  - name: "change resolvconf"
    become: yes
    shell: bash /etc/NetworkManager/dispatcher.d/31_resolvconf vxlan0 up
    tags:
      - resolvconf

  - name: "start_enable nm_dispacher"
    become: yes
    service: name=NetworkManager-dispatcher.service state=started enabled=yes
    tags:
      - hostname
      - resolvconf
