---
  - name: "install dnsmasq packages"
    become: yes
    yum: name=dnsmasq state=present
    tags:
      - dnsmasq

  - name: "create addn-hosts"
    become: yes
    template: src=addn-hosts.j2 dest=/etc/addn-hosts owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "check NetworkManager enabled"
    become: yes
    shell: ps -elf | grep NetworkManager | grep -v grep | wc -l
    ignore_errors: true
    register: isNM_rerult

  - name: "copy dnsmasq.conf"
    become: yes
    template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
    when: isNM_rerult.stdout == "0"
    tags:
      - dnsmasq

  - name: "copy resolv.dnsmasq.conf from /etc/resolv.conf"
    become: yes
    copy: src=resolv.dnsmasq.conf dest=/etc/resolv.dnsmasq.conf owner=root group=root mode=0644
#    shell: cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
#      creates=/etc/resolv.dnsmasq.conf
    when: isNM_rerult.stdout == "0"
    tags:
      - dnsmasq
      
  - name: "start enable dnsmasq"
    become: yes
    service: name=dnsmasq.service state=restarted enabled=yes
    when: isNM_rerult.stdout == "0"
    tags:
      - dnsmasq
