---
  - name: "create addn-hosts"
    become: yes
    template: src=addn-hosts.j2 dest=/etc/addn-hosts owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy dns.conf"
    become: yes
    copy: src=dns.conf dest=/etc/NetworkManager/conf.d/dns.conf owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy hosts"
    become: yes
    copy: src=hosts dest=/etc/NetworkManager/dnsmasq.d/hosts owner=root group=root mode=0644
    tags:
      - dnsmasq
      
  - name: "restart networkManager"
    become: yes
    service: name=NetworkManager.service state=restarted
    tags:
      - dnsmasq

  - name: "create sethosts"
    become: yes
    template: src=30_hostname.j2 dest=/etc/NetworkManager/dispatcher.d/30_hostname owner=root group=root mode=0700
    tags:
      - hostname

  - name: "change hostname"
    become: yes
    shell: bash /etc/NetworkManager/dispatcher.d/30_hostname vxlan0 up
    tags:
      - hostname