---
  - name: "install dnsmasq packages"
    become: yes
    yum: name=dnsmasq state=present
    tags:
      - dnsmasq

  - name: "create addn-hosts"
    become: yes
    template: src=addn-hosts.j2 dest=/etc/addn-hosts owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy dnsmasq.conf"
    become: yes
    template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf owner=root group=root mode=0644
    tags:
      - dnsmasq

  - name: "copy resolv.dnsmasq.conf from /etc/resolv.conf"
    become: yes
    shell: cp /etc/resolv.conf /etc/resolv.dnsmasq.conf
      creates=/etc/resolv.dnsmasq.conf
    tags:
      - dnsmasq

  - name: "add nameserver 8.8.8.8 resolv.dnsmasq.conf"
    become: yes
    lineinfile: state=present create=yes insertafter=EOF line="nameserver 8.8.8.8" dest=/etc/resolv.dnsmasq.conf
    tags:
      - dnsmasq

#### set hostname #################################

  - name: "copy sethost.init(Without NetworkManager)"
    become: yes
    template: src=sethost.init.j2 dest=/usr/local/bin/sethost.init owner=root group=root mode=0700
    tags:
      - sethost
      
  - name: "copy sethost.service(Without NetworkManager)"
    become: yes
    copy: src=sethost.service dest=/etc/systemd/system/sethost.service owner=root group=root mode=0700
    tags:
      - sethost

  - name: "start_enable sethost.service(Without NetworkManager)"
    become: yes
    service: name=sethost.service state=started enabled=yes
    tags:
      - sethost

##### set resolvconf ##########################################

  - name: "check dhclient"
    become: yes
    shell: ps -elf | grep dhclient | grep -v grep | wc -l
    ignore_errors: true
    register: dhclient_rerult

###### for dhclient disable environment (e.g. docker)

  - name: "copy setresolvconf.init(Without NetworkManager)"
    become: yes
    template: src=setresolvconf.init.j2 dest=/usr/local/bin/setresolvconf.init owner=root group=root mode=0700
    when: dhclient_rerult.stdout == "0"
    tags:
      - setresolvconf

  - name: "copy setresolvconf.service(Without NetworkManager)"
    become: yes
    copy: src=sethost.service dest=/etc/systemd/system/setresolvconf.service owner=root group=root mode=0700
    when: dhclient_rerult.stdout == "0"
    tags:
      - setresolvconf

  - name: "start_enable setresolvconf.service(Without NetworkManager)"
    become: yes
    service: name=setresolvconf.service state=started enabled=yes
    when: dhclient_rerult.stdout == "0"
    tags:
      - setresolvconf

###### for dhclient disable environment (e.g. gce/ec2)
  - name: "edit dhclient.conf"
    become: yes
    lineinfile: state=present create=yes insertafter=EOF line="{{ item }}" dest="{{ DHCLIENTCONF }}"
    with_items:
      - "supersede domain-name-servers 127.0.0.1;" 
    when: dhclient_rerult.stdout != "0"
    tags:
      - setresolvconf
      - sethost


##### at last restart dnsmasq.service & network.service
  - name: "start enable dnsmasq.service"
    become: yes
    service: name=dnsmasq.service state=restarted enabled=yes
    tags:
      - setresolvconf
      - sethost    
      - dnsmasq

  - name: "restart network.service"
    become: yes
    service: name=network.service state=restarted
    tags:
      - setresolvconf
      - sethost  
      - dnsmasq
