---
  - name: "create grid/asm.rsp"
    become: yes
    template: src={{ item }}.rsp.j2 dest=/home/grid/{{ item }}.rsp owner=grid group=oinstall mode=0644
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - grid
      - asm
    tags:
      - creategridrsp
      - gridinstall

  - name: "runInstaller(grid)"
    become: yes
    become_user: grid
    shell: "{{ MEDIA_PATH }}/grid/runInstaller -silent -responseFile /home/grid/grid.rsp -waitforcompletion {{ INSTALL_OPS }}"
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    when: inventory_hostname == groups["dbserver"][0]
    register: runinstallergrid_result
    tags:
      - runinstallergrid
      - gridinstall

  - debug: var=runinstallergrid_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - runinstallergrid
      - gridinstall

  - name: "orainstrootsh"
    become: yes
    shell: "{{ ORAINVENTORY }}/orainstRoot.sh -silent"
    register: orainstrootsh_result
    tags:
      - orainstrootsh
      - gridinstall

  - debug: var=orainstrootsh_result.stdout_lines
    tags:
      - orainstrootsh
      - gridinstall

#  - name: "grid root.sh"
#    become: yes
#    shell: "{{ GRID_ORACLE_HOME }}/root.sh -silent"
#    when: inventory_hostname == groups["dbserver"][0]
#    delegate_to: "{{ hostvars[ item.1 ]['ansible_eth0']['ipv4']['address'] }}"
#    with_indexed_items: "{{ groups['dbserver'] }}"
#    register: gridrootsh_result
#    async: "{{ ASYNC }}"
#    poll: "{{ POLL }}"
#    tags:
#      - gridrootsh
#      - gridinstall
#
#  - debug: var=gridrootsh_result.stdout_lines
#    tags:
#      - gridrootsh
#      - gridinstall

  - name: "grid 1st root.sh"
    become: yes
    shell: "{{ GRID_ORACLE_HOME }}/root.sh -silent"
    register: grid1strootsh_result
    when: inventory_hostname == groups["dbserver"][0]
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    tags:
      - grid1strootsh
      - gridrootsh
      - gridinstall

  - debug: var=grid1strootsh_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - grid1strootsh
      - gridrootsh
      - gridinstall

  - name: "grid other root.sh"
    become: yes
    shell: "{{ GRID_ORACLE_HOME }}/root.sh -silent"
    register: gridotherrootsh_result
    when: inventory_hostname != groups["dbserver"][0]
    async: "{{ ASYNC }}"
    poll: "{{ POLL }}"
    tags:
      - gridotherrootsh
      - gridrootsh
      - gridinstall

  - debug: var=gridotherrootsh_result.stdout_lines
    when: inventory_hostname != groups["dbserver"][0]
    tags:
      - gridotherrootsh
      - gridrootsh
      - gridinstall

  - name: "crsctl"
    become: yes
    become_user: grid
    shell: "{{ GRID_ORACLE_HOME }}/bin/crsctl status resource -t"
    register: crsctl_result
    tags:
      - crsctl
      - gridinstall

  - debug: var=crsctl_result.stdout_lines
    tags:
      - crsctl
      - gridinstall



