---
  - name: "create grid/asm.rsp"
    become: yes
    template: src={{ item }}.rsp.j2 dest=/home/grid/{{ item }}.rsp owner=grid group=oinstall mode=0644
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - grid
      - asm
    tags:
      - gridinstall
