---
  - name: "create grid/asm.rsp"
    become: yes
    template: src={{ item }}.rsp.j2 dest=/home/grid/{{ item }}.rsp owner=grid group=oinstall mode=0644
    when: inventory_hostname == groups["dbserver"][0]
    with_items:
      - grid
      - asm
    tags:
      - creategridrsp
      - gridinstall

  - name: "runInstaller(grid)"
    become: yes
    become_user: grid
    shell: /media/grid/runInstaller -silent -responseFile /home/grid/grid.rsp -waitforcompletion {{ INSTALL_OPS }}
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - runinstallergrid
      - gridinstall

  - name: "orainstrootsh"
    become: yes
    shell: "{{ ORAINVENTORY }}"/orainstRoot.sh
    tags:
      - orainstrootsh
      - gridinstall



