---
  - name: "create group"
    become: yes
    group: name={{ item.name }} state=present gid={{ item.gid }}
    with_items:
      - { name: 'oinstall', gid: '601' }
      - { name: 'dba', gid: '602' }
      - { name: 'oper', gid: '603' }
      - { name: 'asmadmin', gid: '2001' }
      - { name: 'asmdba', gid: '2002' }
      - { name: 'asmoper', gid: '2003' }

 