---
  - name: "create diskgroup"
    become: yes
    become_user: grid
    shell : "{{ GRID_ORACLE_HOME }}/bin/asmca -silent -createDiskGroup  -diskGroupName {{ item.name }} -disk {{ item.path }} -redundancy EXTERNAL -au_size 1"
    when: inventory_hostname == groups["dbserver"][0] and storage_type !='nfsmulti'
    register: createdg_result
    with_items:
      - { name: "{{ DATA_DISKGROUP_NAME }}", path: "{{ DATA_DEV }}" }
      - { name: "{{ FRA_DISKGROUP_NAME }}", path: "{{ FRA_DEV }}" }
    tags:
      - createdg
      - installdbca
 
  - name: "create diskgroup" 
    become: yes
    become_user: grid
    shell : "{{ GRID_ORACLE_HOME }}/bin/asmca -silent -createDiskGroup  -diskGroupName {{ item.name }} -redundancy HIGH -au_size 1 {% for host in groups['storage']  %} -disk {{ ORA_DATA }}/{{ hostvars[host]['NODENAME'] }}/{{ item.path }}  {% endfor %}"
    when: inventory_hostname == groups["dbserver"][0] and storage_type == 'nfsmulti'
    register: createdg_result
    with_items:
      - { name: "{{ DATA_DISKGROUP_NAME }}", path: "{{ DATA_FILE }}" }
      - { name: "{{ FRA_DISKGROUP_NAME }}", path: "{{ FRA_FILE }}" }
    tags:
      - createdg
      - installdbca   
