---
  - name: "install epel"
    become: yes
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=present
    tags:
      - xrdp

  - name: "dummy yum command (GPGKEY INSTALL)"
    become: yes
    shell: yum -y search nfs-utils
    ignore_errors: true
    tags:
      - xrdp
      
  - name: "install GNOME,xrdp"
    become: yes
    yum: name={{ item }} state=present
    with_items:
      - "@Server With GUI"
      - vnc-server
      - xrdp
      - firefox
    tags:
      - xrdp

  - name: "enable xrdp"
    become: yes
    service: name=xrdp enabled=yes
    tags:
      - xrdp

  - name: "chcon"
    become: yes
    shell: chcon -t bin_t /usr/sbin/xrdp /usr/sbin/xrdp-sesman
    tags:
      - xrdp

  - name: "edit xrdp.ini"
    become: yes
    shell: sed -i -e 's/max_bpp=32/max_bpp=24/g' /etc/xrdp/xrdp.ini
    tags:
      - xrdp

  - name: "enable xrdp"
    become: yes
    service: name=xrdp state=started
    tags:
      - xrdp

  - name: "create xrdp user"
    become: yes
    user: name="xrdpuser" shell="/bin/bash"  password="{{ xrdpuserpass | password_hash('sha512') }}"
    tags:
      - xrdpusercreate
      - xrdp
