---
  - name: "install jdbcrunner dependency library"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - git
      - java-1.7.0-openjdk-devel
      - ant
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: "create user"
    become: yes
    become_user: oracle
    script: createuser.sh --some-arguments "{{ SIDNAME }}1"
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner   

  - name:
    git:
      repo: 'https://foosball.example.org/path/to/repo.git'
      dest: /srv/checkout
