---
  - name: "install jdbcrunner dependency library"
    become: yes
    yum: name="{{ item }}" state=present
    with_items:
      - git
#      - java-1.7.0-openjdk-devel
      - ant
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: "create user"
    become: yes
    become_user: oracle
    script: createuser.sh "{{ SIDNAME }}1"
    when: inventory_hostname == groups["dbserver"][0]
    register: createuser_result
    tags:
      - jdbcrunner   


  - debug: var=createuser_result.stdout_lines
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner

  - name:
    become: yes
    become_user: oracle
    git:
      repo: https://github.com/sh2/jdbcrunner.git
      dest: /home/oracle/jdbcrunner
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: ant
    become: yes
    become_user: oracle
    shell: /usr/bin/ant && touch ant.txt
    args:
      chdir: /home/oracle/jdbcrunner
      creates: ant.txt
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
  
  - name: copy jdbc driver
    become: yes
    become_user: oracle
    shell: scp {{ ORA_ORACLE_HOME }}/jdbc/lib/ojdbc8.jar oracle@{{ hostvars[groups['client'][0]]["ansible_vxlan0"]['ipv4']['address'] }}:/home/oracle/jdbcrunner/lib
    when: inventory_hostname == groups["dbserver"][0]
    tags:
      - jdbcrunner

  - name: load tpcc data
    become: yes
    become_user: oracle
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3.jar:lib/* JR scripts/tpcc_load.js -jdbcUrl jdbc:oracle:thin:@{{ hostvars[groups['dbserver'][0]]['ansible_vxlan0']['ipv4']['address'] }}:1521:{{ SIDNAME }}1"
    args:
      chdir: /home/oracle/jdbcrunner
    when: inventory_hostname == groups["client"][0]
    register: tpccload_result
    tags:
      - jdbcrunner


  - debug: var=tpccload_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner

  - name: exec tpcc
    become: yes
    become_user: oracle
    shell: "/usr/bin/java -Djava.security.egd=file:/dev/./urandom -cp jdbcrunner-1.3.jar:lib/* JR scripts/tpcc.js -trace -debug -nAgents 1 -measurementTime 60 -warmupTime 10 -jdbcUrl 'jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=yes)(ADDRESS=(PROTOCOL=TCP)(HOST=node001)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=node002)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=node003)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME={{ SIDNAME }})))'"
    args:
      chdir: /home/oracle/jdbcrunner
    when: inventory_hostname == groups["client"][0]
    async: 3000
    poll: 10
    register: tpcc_result
    tags:
      - jdbcrunner
      - tpcc_exec

  - debug: var=tpcc_result.stdout_lines
    when: inventory_hostname == groups["client"][0]
    tags:
      - jdbcrunner
      - tpcc_exec
